os: linux
dist: xenial
language: node_js
node_js:
  - 12
  - 10

#addons:
#  rethinkdb: '2.3'
before_install:
  - source /etc/lsb-release && echo "deb https://download.rethinkdb.com/repository/ubuntu-$DISTRIB_CODENAME $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/repository/raw/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y rethinkdb
  - sudo service rethinkdb start 
script: true
